# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastralEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FamilyName', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('FirstName', models.CharField(max_length=100, verbose_name='Имя')),
                ('Patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('CadastralEngineerRegistryNumber', models.CharField(max_length=50, verbose_name='Номер квалификационного аттестата кадастрового инженера')),
                ('Telephone', models.CharField(max_length=50, verbose_name='Контактный телефон')),
                ('Address', models.TextField(max_length=4000, verbose_name='Почтовый адрес для связи с кадастровым инженером')),
                ('Email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='engineer', unique=True)),
            ],
            options={
                'verbose_name': 'Сведения о кадастровом инженере',
            },
        ),
    ]
